apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "job-orchestration.componentName" (dict "Release" .Release "component" "keycloak") }}
  labels:
    {{- include "job-orchestration.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  replicas: {{ .Values.keycloak.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: keycloak
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "job-orchestration.labels" . | nindent 8 }}
        app.kubernetes.io/component: keycloak
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          args:
            - start-dev
          ports:
            - containerPort: {{ .Values.keycloak.service.targetPort }}
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.keycloak.env.adminUser | quote }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.keycloak.env.adminPassword | quote }}
