apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "job-orchestration.componentName" (dict "Release" .Release "component" "orchestrator") }}
  labels:
    {{- include "job-orchestration.labels" . | nindent 4 }}
    app.kubernetes.io/component: orchestrator
spec:
  replicas: {{ .Values.orchestrator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: orchestrator
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "job-orchestration.labels" . | nindent 8 }}
        app.kubernetes.io/component: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: "{{ .Values.orchestrator.image.repository }}:{{ .Values.orchestrator.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.orchestrator.service.targetPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.orchestrator.env.springProfilesActive | quote }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.orchestrator.env.datasourceUrl | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.orchestrator.env.datasourceUsername | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.orchestrator.env.datasourcePassword | quote }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: {{ .Values.orchestrator.env.issuerUri | quote }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.orchestrator.env.kafkaBootstrapServers | quote }}
