apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "job-orchestration.componentName" (dict "Release" .Release "component" "worker") }}
  labels:
    {{- include "job-orchestration.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "job-orchestration.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.worker.service.targetPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.worker.env.springProfilesActive | quote }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.worker.env.kafkaBootstrapServers | quote }}
            - name: WORKER_KAFKA_WORK_TOPIC
              value: {{ .Values.worker.env.workTopic | quote }}
            - name: WORKER_KAFKA_EVENT_TOPIC
              value: {{ .Values.worker.env.eventTopic | quote }}
